[workspace]
changelog_update = false
git_release_enable = false
git_tag_enable = false
publish = true
publish_timeout = "30m"
release_always = false

[changelog]
commit_parsers = [
    { message = "^Merge", skip = true },
    { message = "^feat", group = "Added" },
    { message = "^test\\(e2e\\)", group = "Changed" },
    { message = "^test", group = "Added" },
    { message = "^(perf|refactor)", group = "Changed" },
    { message = "^fix", group = "Fixed" },
    { message = "^(docs|chore|ci|build)", skip = true },
    { message = ".*", skip = true },
]

[[package]]
name = "tronz"
changelog_include = [
    "tronz-abi",
    "tronz-contract",
    "tronz-primitives",
    "tronz-provider",
    "tronz-rpc-types",
    "tronz-signer",
    "tronz-signer-aws",
    "tronz-sol-macro",
]
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
git_release_name = "v{{ version }}"
git_tag_enable = true
git_tag_name = "v{{ version }}"
