//! Workspace tasks.
//!
//! `cargo xtask codegen` regenerates the protobuf bindings that are committed to
//! the tree. It is the only thing in the workspace that runs `protoc`, so
//! building or publishing any crate never needs it installed.

use std::{
    error::Error,
    fs,
    path::{Path, PathBuf},
};

/// Payloads large enough that copying them out of the response frame costs real
/// work. Fixed-size identifiers and UTF-8-like fields stay `Vec<u8>`, so they do
/// not pin an entire frame in memory for the sake of 32 bytes.
const BYTES_FIELDS: &[&str] = &[
    ".protocol.TransactionExtention.constant_result",
    ".protocol.TriggerSmartContract.data",
    ".protocol.SmartContract.bytecode",
    ".protocol.SmartContractDataWrapper.runtimecode",
    ".protocol.TransactionInfo.Log.data",
    ".protocol.Transaction.raw.data",
    ".protocol.Transaction.signature",
];

/// Every message in the `protocol` package belongs to this crate, and this is
/// the module path the service clients are pointed at.
const MESSAGES_MODULE: &str = "::tronz_rpc_types::proto";

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = std::env::args().skip(1);

    match (args.next().as_deref(), args.next().as_deref()) {
        (Some("codegen"), None) => codegen(Mode::Write),
        (Some("codegen"), Some("--check")) => codegen(Mode::Check),
        (Some(other), _) => Err(format!("unknown task `{other}`; try `codegen`").into()),
        (None, _) => Err("usage: cargo xtask codegen [--check]".into()),
    }
}

/// Whether to update the committed files or to fail if they are out of date.
#[derive(Clone, Copy, PartialEq)]
enum Mode {
    Write,
    Check,
}

/// Compiles the schema twice: once for the messages, once for the clients that
/// carry them. The second pass maps the whole `protocol` package onto the first,
/// so exactly one crate defines each message.
fn codegen(mode: Mode) -> Result<(), Box<dyn Error>> {
    let root = repo_root();
    let proto_root = root.join("crates/rpc-types/proto");
    let entry = proto_root.join("tron/api/api.proto");
    // Core messages import each other relative to `tron/`, while `api.proto`
    // imports the Google annotations relative to the root.
    let tron = proto_root.join("tron");
    let includes = [&tron, &proto_root];

    let scratch = root.join("target/xtask-codegen");
    let messages_out = scratch.join("messages");
    let services_out = scratch.join("services");
    fs::create_dir_all(&messages_out)?;
    fs::create_dir_all(&services_out)?;

    let mut messages = prost_build::Config::new();
    messages.out_dir(&messages_out);
    // One call with every path: `Config::bytes` replaces the set rather than
    // adding to it, so calling it per field would keep only the last.
    messages.bytes(BYTES_FIELDS);
    messages.compile_protos(&[&entry], &includes)?;

    tonic_prost_build::configure()
        .build_server(false)
        .extern_path(".protocol", MESSAGES_MODULE)
        .out_dir(&services_out)
        .compile_protos(&[&entry], &includes)?;

    // `api.proto` imports the Google HTTP annotations, so `protoc` writes a
    // `google.api.rs` next to each `protocol.rs`. The annotations are options and
    // reach no generated Rust, so neither file is kept.
    let mut stale = Vec::new();
    for (from, to, what) in [
        (
            messages_out.join("protocol.rs"),
            root.join("crates/rpc-types/src/generated/protocol.rs"),
            "the `protocol` protobuf messages",
        ),
        (
            services_out.join("protocol.rs"),
            root.join("crates/provider/src/generated/services.rs"),
            "the gRPC service clients",
        ),
    ] {
        if !install(&from, &to, what, mode)? {
            stale.push(to);
        }
    }

    if !stale.is_empty() {
        let names: Vec<_> = stale.iter().map(|p| p.display().to_string()).collect();
        return Err(format!(
            "out of date with the schema: {}\nrun `cargo xtask codegen`",
            names.join(", ")
        )
        .into());
    }

    Ok(())
}

/// Puts a generated file into the tree under a header that says where it came
/// from, so nobody edits it by hand.
///
/// In [`Mode::Check`] it writes nothing, and reports whether what is committed is
/// what the schema produces.
fn install(from: &Path, to: &Path, what: &str, mode: Mode) -> Result<bool, Box<dyn Error>> {
    let header = format!(
        "// Generated by `cargo xtask codegen` from `crates/rpc-types/proto`: {what}.\n\
         // Do not edit by hand; edit the schema and regenerate.\n\n"
    );
    let wanted = header + &fs::read_to_string(from)?;

    if mode == Mode::Check {
        let current = fs::read_to_string(to).unwrap_or_default();
        let matches = current == wanted;
        println!("{}: {}", to.display(), if matches { "up to date" } else { "STALE" });
        return Ok(matches);
    }

    fs::create_dir_all(to.parent().expect("generated files live in a directory"))?;
    fs::write(to, wanted)?;

    println!("wrote {}", to.display());
    Ok(true)
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask sits one level below the workspace root")
        .to_path_buf()
}
