//! [`TronEventFilter`] — query and decode typed contract events on TRON.

use std::marker::PhantomData;

use alloy_primitives::B256;
use alloy_sol_types::SolEvent;
use tronz_primitives::{Address, TxId};
use tronz_provider::{Error as ProviderError, TronProvider, types::Log};

use crate::error::{ContractError, Result};

/// A typed event filter bound to a specific contract address and provider.
///
/// Created by `Instance::event_filter::<E>()` (the generic entry point) or by
/// the per-event convenience methods generated by `tron_sol!` (e.g.
/// `token.Transfer_filter()`).
///
/// # Querying
///
/// TRON does not expose an Ethereum-style `eth_getLogs` RPC.  Two query paths
/// are available:
///
/// | Method | What it scans |
/// |--------|---------------|
/// | [`query_tx`](Self::query_tx) | logs emitted by one transaction |
/// | [`query_block`](Self::query_block) | logs emitted by every transaction in a block |
///
/// For a block range, call `query_block` in a loop.
pub struct TronEventFilter<P, E> {
    provider: P,
    address: Option<Address>,
    _event: PhantomData<fn() -> E>,
}

impl<P: TronProvider, E: SolEvent> TronEventFilter<P, E> {
    /// Create a new filter, optionally restricted to a specific contract address.
    pub fn new(provider: P, address: Option<Address>) -> Self {
        Self {
            provider,
            address,
            _event: PhantomData,
        }
    }

    /// Narrow the filter to a specific contract address.
    #[inline]
    pub fn address(mut self, address: Address) -> Self {
        self.address = Some(address);
        self
    }

    /// Collect all matching events emitted by a single transaction.
    pub async fn query_tx(&self, tx_id: TxId) -> Result<Vec<E>> {
        let info = self
            .provider
            .get_transaction_info(tx_id)
            .await
            .map_err(ContractError::Provider)?
            .ok_or_else(|| {
                ContractError::Provider(ProviderError::local_usage_str("transaction not found"))
            })?;
        Ok(self.decode_logs(&info.logs))
    }

    /// Collect all matching events emitted by any transaction in `block_num`.
    pub async fn query_block(&self, block_num: i64) -> Result<Vec<E>> {
        let infos = self
            .provider
            .get_transaction_info_by_block_num(block_num)
            .await
            .map_err(ContractError::Provider)?;
        Ok(infos
            .iter()
            .flat_map(|info| self.decode_logs(&info.logs))
            .collect())
    }

    // ── internal ──────────────────────────────────────────────────────────────

    fn decode_logs(&self, logs: &[Log]) -> Vec<E> {
        let sig: B256 = E::SIGNATURE_HASH;
        logs.iter()
            .filter(|log| {
                // both conditions must hold: emitter address (if filtered) and
                // topic0 matching the event signature hash
                self.address.is_none_or(|a| log.address == a)
                    && log.topics.first().copied() == Some(sig)
            })
            .filter_map(|log| E::decode_raw_log(log.topics.iter().copied(), &log.data).ok())
            .collect()
    }
}
